[profile.default]
src = 'src'
out = 'forge-artifacts'
script = 'scripts'
optimizer = true
optimizer_runs = 999999
extra_output = ['devdoc', 'userdoc', 'metadata', 'storageLayout']
bytecode_hash = 'none'
build_info = true
build_info_path = 'artifacts/build-info'
ffi = true
fuzz_runs = 16

fs_permissions = [
  { 'access'='read-write', 'path'='./.resource-metering.csv' },
  { 'access'='read-write', 'path'='./deployments/' },
  { 'access'='read', 'path'='./deploy-config/' },
  { 'access'='read', 'path'='./broadcast/' },
  { access = 'read', path = './forge-artifacts/' },
  { 'access'='write', 'path'='./semver-lock.json' },
]

[profile.ci]
fuzz_runs = 512
